events {}

http {
    server {
        listen 443 ssl;

        ssl_certificate /etc/ssl/server.crt;
        ssl_certificate_key /etc/ssl/server.key;

        location / {
            proxy_pass http://api:8443;
        }
    }
}


